version: 1
formatters:
  standard:
    format: '%(asctime)s | %(levelname)s | %(name)s | %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
loggers:
  geo_analyzer:
    handlers: [console]
    level: INFO
    propagate: false
root:
  handlers: [console]
  level: INFO
